//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaKaydıTbl
    {
        public string HastaTC { get; set; }
        public int HastaneID { get; set; }
        public string HastaAdı { get; set; }
        public string HastaSoyad { get; set; }
        public string Tel { get; set; }
        public int BolumID { get; set; }
    
        public virtual BolumTbl BolumTbl { get; set; }
        public virtual HastaneTbl HastaneTbl { get; set; }
    }
}
