//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaneTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HastaneTbl()
        {
            this.HastaKaydıTbl = new HashSet<HastaKaydıTbl>();
            this.RandevuTbl = new HashSet<RandevuTbl>();
        }
    
        public int HastaneID { get; set; }
        public int SehirKod { get; set; }
        public string HastaneAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaKaydıTbl> HastaKaydıTbl { get; set; }
        public virtual SehirTbl SehirTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RandevuTbl> RandevuTbl { get; set; }
    }
}
