//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RandevuTbl
    {
        public int RandevuID { get; set; }
        public System.DateTime RandevuGunu { get; set; }
        public int HastaneID { get; set; }
        public string YeniHastaTC { get; set; }
    
        public virtual HastaneTbl HastaneTbl { get; set; }
    }
}
