//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databasa
{
    using System;
    using System.Collections.Generic;
    
    public partial class BolumTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BolumTbl()
        {
            this.DoktorTbl = new HashSet<DoktorTbl>();
            this.HastaKaydıTbl = new HashSet<HastaKaydıTbl>();
        }
    
        public int BolumID { get; set; }
        public string BolumAdı { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoktorTbl> DoktorTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaKaydıTbl> HastaKaydıTbl { get; set; }
    }
}
