//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDatabaseEntities : DbContext
    {
        public HospitalDatabaseEntities()
            : base("name=HospitalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BolumTbl> BolumTbl { get; set; }
        public virtual DbSet<DoktorTbl> DoktorTbl { get; set; }
        public virtual DbSet<HastaKaydıTbl> HastaKaydıTbl { get; set; }
        public virtual DbSet<HastaneTbl> HastaneTbl { get; set; }
        public virtual DbSet<IzinTbl> IzinTbl { get; set; }
        public virtual DbSet<RandevuTbl> RandevuTbl { get; set; }
        public virtual DbSet<SehirTbl> SehirTbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
